// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: bookpb/book.proto

package bookpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BookSearchByTitleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *BookSearchByTitleRequest) Reset() {
	*x = BookSearchByTitleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bookpb_book_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookSearchByTitleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookSearchByTitleRequest) ProtoMessage() {}

func (x *BookSearchByTitleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookpb_book_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookSearchByTitleRequest.ProtoReflect.Descriptor instead.
func (*BookSearchByTitleRequest) Descriptor() ([]byte, []int) {
	return file_bookpb_book_proto_rawDescGZIP(), []int{0}
}

func (x *BookSearchByTitleRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type BookSearchByAuthorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Author string `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
}

func (x *BookSearchByAuthorRequest) Reset() {
	*x = BookSearchByAuthorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bookpb_book_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookSearchByAuthorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookSearchByAuthorRequest) ProtoMessage() {}

func (x *BookSearchByAuthorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookpb_book_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookSearchByAuthorRequest.ProtoReflect.Descriptor instead.
func (*BookSearchByAuthorRequest) Descriptor() ([]byte, []int) {
	return file_bookpb_book_proto_rawDescGZIP(), []int{1}
}

func (x *BookSearchByAuthorRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

type BookSearchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Book *Book `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
}

func (x *BookSearchResponse) Reset() {
	*x = BookSearchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bookpb_book_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookSearchResponse) ProtoMessage() {}

func (x *BookSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bookpb_book_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookSearchResponse.ProtoReflect.Descriptor instead.
func (*BookSearchResponse) Descriptor() ([]byte, []int) {
	return file_bookpb_book_proto_rawDescGZIP(), []int{2}
}

func (x *BookSearchResponse) GetBook() *Book {
	if x != nil {
		return x.Book
	}
	return nil
}

type Book struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title    string  `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Subject  string  `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Audience string  `protobuf:"bytes,3,opt,name=audience,proto3" json:"audience,omitempty"`
	Author   string  `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Price    float32 `protobuf:"fixed32,5,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *Book) Reset() {
	*x = Book{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bookpb_book_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_bookpb_book_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_bookpb_book_proto_rawDescGZIP(), []int{3}
}

func (x *Book) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Book) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Book) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

func (x *Book) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Book) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_bookpb_book_proto protoreflect.FileDescriptor

var file_bookpb_book_proto_rawDesc = []byte{
	0x0a, 0x11, 0x62, 0x6f, 0x6f, 0x6b, 0x70, 0x62, 0x2f, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x62, 0x6f, 0x6f, 0x6b, 0x22, 0x30, 0x0a, 0x18, 0x42, 0x6f, 0x6f,
	0x6b, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x79, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x22, 0x33, 0x0a, 0x19, 0x42,
	0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x79, 0x41, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x22, 0x34, 0x0a, 0x12, 0x42, 0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x04, 0x62, 0x6f, 0x6f, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x42, 0x6f, 0x6f, 0x6b,
	0x52, 0x04, 0x62, 0x6f, 0x6f, 0x6b, 0x22, 0x80, 0x01, 0x0a, 0x04, 0x42, 0x6f, 0x6f, 0x6b, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x61, 0x75, 0x64, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x61, 0x75, 0x64, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x32, 0xb0, 0x01, 0x0a, 0x0a, 0x42, 0x6f,
	0x6f, 0x6b, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x4f, 0x0a, 0x11, 0x62, 0x6f, 0x6f, 0x6b,
	0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x79, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1e, 0x2e,
	0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42,
	0x79, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e,
	0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x51, 0x0a, 0x12, 0x62, 0x6f, 0x6f,
	0x6b, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x79, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12,
	0x1f, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x42, 0x79, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x18, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x24, 0x5a, 0x22,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x67, 0x6f, 0x2d, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x2f,
	0x62, 0x6f, 0x6f, 0x6b, 0x2d, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2f, 0x62, 0x6f, 0x6f, 0x6b,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bookpb_book_proto_rawDescOnce sync.Once
	file_bookpb_book_proto_rawDescData = file_bookpb_book_proto_rawDesc
)

func file_bookpb_book_proto_rawDescGZIP() []byte {
	file_bookpb_book_proto_rawDescOnce.Do(func() {
		file_bookpb_book_proto_rawDescData = protoimpl.X.CompressGZIP(file_bookpb_book_proto_rawDescData)
	})
	return file_bookpb_book_proto_rawDescData
}

var file_bookpb_book_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_bookpb_book_proto_goTypes = []interface{}{
	(*BookSearchByTitleRequest)(nil),  // 0: book.BookSearchByTitleRequest
	(*BookSearchByAuthorRequest)(nil), // 1: book.BookSearchByAuthorRequest
	(*BookSearchResponse)(nil),        // 2: book.BookSearchResponse
	(*Book)(nil),                      // 3: book.Book
}
var file_bookpb_book_proto_depIdxs = []int32{
	3, // 0: book.BookSearchResponse.book:type_name -> book.Book
	0, // 1: book.BookSearch.bookSearchByTitle:input_type -> book.BookSearchByTitleRequest
	1, // 2: book.BookSearch.bookSearchByAuthor:input_type -> book.BookSearchByAuthorRequest
	2, // 3: book.BookSearch.bookSearchByTitle:output_type -> book.BookSearchResponse
	2, // 4: book.BookSearch.bookSearchByAuthor:output_type -> book.BookSearchResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bookpb_book_proto_init() }
func file_bookpb_book_proto_init() {
	if File_bookpb_book_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bookpb_book_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookSearchByTitleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bookpb_book_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookSearchByAuthorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bookpb_book_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookSearchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bookpb_book_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Book); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bookpb_book_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bookpb_book_proto_goTypes,
		DependencyIndexes: file_bookpb_book_proto_depIdxs,
		MessageInfos:      file_bookpb_book_proto_msgTypes,
	}.Build()
	File_bookpb_book_proto = out.File
	file_bookpb_book_proto_rawDesc = nil
	file_bookpb_book_proto_goTypes = nil
	file_bookpb_book_proto_depIdxs = nil
}
